name: Feature Request
description: Suggest an idea for IntelliSFIA
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make IntelliSFIA better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see [...]
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - User Interface
        - API Enhancement
        - Integration
        - Performance
        - Security
        - AI/ML Feature
        - Reporting/Analytics
        - Mobile
        - Administration
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Type
      description: Who would primarily benefit from this feature?
      options:
        - End Users (Employees)
        - Managers/Team Leads
        - HR Professionals
        - System Administrators
        - Developers/Integrators
        - Executives/Leadership
        - All Users
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [situation], this feature would help by [benefit]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Significantly impacts productivity
        - Critical - Blocking current work
    validations:
      required: true

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you ideally like to see this feature?
      placeholder: e.g. Next quarter, End of year, No specific timeline

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects, constraints, or implementation ideas you'd like to share

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have mockups, wireframes, or examples from other tools, please share them here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: By submitting this feature request, you confirm that
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: This feature would benefit multiple users, not just my specific use case
          required: true
        - label: I have provided sufficient detail for the development team to understand the request
          required: true