groups:
  - name: intellisfia.rules
    interval: 30s
    rules:
      # Application health and availability
      - alert: ServiceDown
        expr: up{job=~"api-gateway|sfia-engine|rdf-service|frontend"} == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "IntelliSFIA service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate on {{ $labels.job }} is {{ $value | humanizePercentage }} for more than 2 minutes."

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 3m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "95th percentile response time on {{ $labels.job }} is {{ $value }}s for more than 3 minutes."

      # Database alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: postgresql
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute."

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 2m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL connection usage is {{ $value | humanizePercentage }} for more than 2 minutes."

      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
        for: 5m
        labels:
          severity: warning
          service: postgresql
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "PostgreSQL query efficiency is low ({{ $value | humanizePercentage }}) for more than 5 minutes."

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis cache server has been down for more than 1 minute."

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 2m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }} for more than 2 minutes."

      # System resource alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage on {{ $labels.instance }} is {{ $value }}% for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.8
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage on {{ $labels.instance }} is {{ $value | humanizePercentage }} for more than 5 minutes."

      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) > 0.8
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk usage on {{ $labels.instance }} ({{ $labels.mountpoint }}) is {{ $value | humanizePercentage }}."

      # Application-specific alerts
      - alert: HighUserRegistrationRate
        expr: rate(user_registrations_total[5m]) > 10
        for: 1m
        labels:
          severity: info
          service: api-gateway
        annotations:
          summary: "High user registration rate"
          description: "User registration rate is {{ $value }} registrations per second."

      - alert: FailedLogins
        expr: rate(failed_login_attempts_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: api-gateway
        annotations:
          summary: "High failed login rate"
          description: "Failed login rate is {{ $value }} attempts per second for more than 2 minutes."

      - alert: AssessmentProcessingTime
        expr: histogram_quantile(0.95, rate(assessment_processing_duration_seconds_bucket[5m])) > 30
        for: 3m
        labels:
          severity: warning
          service: sfia-engine
        annotations:
          summary: "Slow assessment processing"
          description: "95th percentile assessment processing time is {{ $value }}s for more than 3 minutes."

      # Container and infrastructure alerts
      - alert: ContainerDown
        expr: up{job="cadvisor"} == 0
        for: 1m
        labels:
          severity: warning
          service: monitoring
        annotations:
          summary: "cAdvisor is down"
          description: "Container monitoring (cAdvisor) has been down for more than 1 minute."

      - alert: HighContainerCPU
        expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: containers
        annotations:
          summary: "High CPU usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} CPU usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      - alert: HighContainerMemory
        expr: container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes > 0.8
        for: 3m
        labels:
          severity: warning
          service: containers
        annotations:
          summary: "High memory usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} memory usage is {{ $value | humanizePercentage }} for more than 3 minutes."

      # SSL certificate expiration
      - alert: SSLCertificateExpiring
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1h
        labels:
          severity: warning
          service: nginx
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value | humanizeDuration }}."

      - alert: SSLCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() < 0
        for: 1m
        labels:
          severity: critical
          service: nginx
        annotations:
          summary: "SSL certificate expired"
          description: "SSL certificate for {{ $labels.instance }} has expired."