global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'intellisfia-prod'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics via nginx-prometheus-exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # IntelliSFIA API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # IntelliSFIA SFIA Engine
  - job_name: 'sfia-engine'
    static_configs:
      - targets: ['sfia-engine:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # IntelliSFIA RDF Service
  - job_name: 'rdf-service'
    static_configs:
      - targets: ['rdf-service:8002']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # GraphDB metrics (if available)
  - job_name: 'graphdb'
    static_configs:
      - targets: ['graphdb:7200']
    scrape_interval: 30s
    metrics_path: /rest/monitor/infrastructure
    scrape_timeout: 10s

  # RabbitMQ Management metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s
    metrics_path: /metrics

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
    metrics_path: /minio/v2/metrics/cluster
    bearer_token: 'minio-metrics-token'

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: /_prometheus/metrics

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: /metrics

  # Frontend metrics (if implemented)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 60s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Custom application metrics from load balancer
  - job_name: 'nginx-internal'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /metrics

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "prometheus"
#       password: "your-password"

# Additional configuration can be added via command line flags in docker-compose